package com.fantasy.bff.dto.response;

import com.fantasy.bff.generated.db.model.PlayerProjection;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

/**
 * Model-generated projection lines, ready to be dropped into a new projection.
 *
 * <p>Only the players are produced here. Scoring settings belong to the user's league, so the
 * client keeps those and combines the two when it saves.
 */
@Schema(description = "Projection lines generated by the model, keyed by the platform's player id")
public record SeededProjectionResponse(
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED) List<PlayerProjection> players,
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Season the lines project")
                int season,
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Model version behind them")
                String modelVersion,
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED) int skaters,
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED) int goalies,
        @Schema(
                        requiredMode = Schema.RequiredMode.REQUIRED,
                        description =
                                "Projected players with no counterpart on this platform. Mostly fringe "
                                        + "and long-term absent players the platform doesn't carry.")
                int unmapped,
        @Schema(
                        requiredMode = Schema.RequiredMode.REQUIRED,
                        description =
                                "Goalies the model projects no starts for, not counted in `goalies`. "
                                        + "Their lines are in `players` at zero starts with no save "
                                        + "percentage or GAA, since a zero there would read as the "
                                        + "worst goalie in the league.")
                int goaliesWithoutWorkload) {}
