package com.fantasy.bff.service.scoring;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import com.fantasy.bff.dto.response.RosterSlots;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Holds this engine to the web's, cell by cell.
 *
 * <p>Two implementations of one ranking is a thing that drifts, and a league scored differently
 * on two surfaces is worse than a league not scored here at all: the board a manager drafted on
 * and the summary he is sent afterwards would disagree about who won his draft. So the numbers
 * are not compared by eye or by property — the web computes them, commits them
 * (`fantasy-web/src/app/draft-mode/scoring-vectors.json`, generated by its own spec) and this
 * test replays the same leagues through the Java engine.
 *
 * <p>On a deliberate change to how a board is scored: change the web, regenerate there with
 * `UPDATE_SCORING_VECTORS=1 npm test`, and re-pin the file here in the same change, the way a
 * downstream spec is pinned. A failure with no such change means one side moved on its own.
 */
class LeagueSummaryGoldenVectorTest {

    /** The numbers are the same arithmetic in both languages; this is room for the last bit. */
    private static final double TOLERANCE = 1e-9;

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final LeagueSummaryCalculator calculator = new LeagueSummaryCalculator();

    @Test
    @DisplayName("scores every committed league exactly as the web scored it")
    void matchesTheWebsVectors() throws Exception {
        JsonNode vectors = readVectors();
        assertThat(vectors.get("cases")).as("committed cases").isNotEmpty();

        for (JsonNode entry : vectors.get("cases")) {
            JsonNode testCase = entry.get("case");
            String name = testCase.get("name").asText();
            LeagueSummary summary = calculator.summarise(
                    pool(testCase.get("pool")),
                    teams(testCase.get("teams")),
                    league(testCase.get("league")));
            assertSummary(name, summary, entry.get("expected"));
        }
    }

    private void assertSummary(String name, LeagueSummary summary, JsonNode expected) {
        assertThat(summary.categoryKeys()).as("%s: category keys", name)
                .isEqualTo(strings(expected.get("categoryKeys")));
        assertThat(summary.positionKeys()).as("%s: position keys", name)
                .isEqualTo(strings(expected.get("positionKeys")));

        JsonNode expectedTeams = expected.get("teams");
        assertThat(summary.teams()).as("%s: teams", name).hasSize(expectedTeams.size());
        for (int index = 0; index < expectedTeams.size(); index++) {
            LeagueSummary.Team team = summary.teams().get(index);
            JsonNode expectedTeam = expectedTeams.get(index);
            String where = "%s: %s".formatted(name, expectedTeam.get("teamId").asText());

            // The order is the table's own: teams come back best total first.
            assertThat(team.teamId()).as("%s: place %d", name, index + 1)
                    .isEqualTo(expectedTeam.get("teamId").asText());
            assertThat(team.total()).as("%s: total", where)
                    .isCloseTo(expectedTeam.get("total").asDouble(), within(TOLERANCE));

            JsonNode expectedValues = expectedTeam.get("values");
            expectedValues.fieldNames().forEachRemaining(key ->
                    assertThat(team.values().get(key)).as("%s: cell %s", where, key)
                            .isCloseTo(expectedValues.get(key).asDouble(), within(TOLERANCE)));
            assertThat(team.values().keySet()).as("%s: cells", where)
                    .containsExactlyInAnyOrderElementsOf(fieldNames(expectedValues));

            assertRoster(where, team.roster(), expectedTeam.get("roster"));
            assertPositions(where, team.positionPlayers(), expectedTeam.get("positionPlayers"));
        }
    }

    private void assertRoster(String where, List<LeagueSummary.RosterRow> roster, JsonNode expected) {
        assertThat(roster).as("%s: roster", where).hasSize(expected.size());
        for (int index = 0; index < expected.size(); index++) {
            LeagueSummary.RosterRow row = roster.get(index);
            JsonNode expectedRow = expected.get(index);
            String rowWhere = "%s: roster %d".formatted(where, index + 1);

            assertThat(row.name()).as("%s name", rowWhere).isEqualTo(expectedRow.get("name").asText());
            assertThat(row.total()).as("%s total", rowWhere)
                    .isCloseTo(expectedRow.get("total").asDouble(), within(TOLERANCE));
            assertNullableNumbers(rowWhere + " values", row.values(), expectedRow.get("values"));
            assertNullableNumbers(
                    rowWhere + " contributions", row.contributions(), expectedRow.get("contributions"));
        }
    }

    /**
     * A stat of the other kind is null rather than zero — a goalie has no hits, which is not the
     * same as a goalie who lands none — so the nulls are part of what has to match.
     */
    private void assertNullableNumbers(String where, Map<String, Double> actual, JsonNode expected) {
        assertThat(actual.keySet()).as("%s: keys", where)
                .containsExactlyInAnyOrderElementsOf(fieldNames(expected));
        expected.fieldNames().forEachRemaining(key -> {
            JsonNode value = expected.get(key);
            if (value.isNull()) {
                assertThat(actual.get(key)).as("%s: %s", where, key).isNull();
            } else {
                assertThat(actual.get(key)).as("%s: %s", where, key)
                        .isCloseTo(value.asDouble(), within(TOLERANCE));
            }
        });
    }

    private void assertPositions(
            String where, Map<String, List<LeagueSummary.Contributor>> actual, JsonNode expected) {
        assertThat(actual.keySet()).as("%s: lineup slots", where)
                .containsExactlyInAnyOrderElementsOf(fieldNames(expected));
        expected.fieldNames().forEachRemaining(slot -> {
            JsonNode expectedPlayers = expected.get(slot);
            List<LeagueSummary.Contributor> players = actual.get(slot);
            assertThat(players).as("%s: slot %s", where, slot).hasSize(expectedPlayers.size());
            for (int index = 0; index < expectedPlayers.size(); index++) {
                assertThat(players.get(index).name()).as("%s: slot %s, place %d", where, slot, index + 1)
                        .isEqualTo(expectedPlayers.get(index).get("name").asText());
                assertThat(players.get(index).value()).as("%s: slot %s, value %d", where, slot, index + 1)
                        .isCloseTo(expectedPlayers.get(index).get("value").asDouble(), within(TOLERANCE));
            }
        });
    }

    private JsonNode readVectors() throws Exception {
        try (InputStream stream =
                getClass().getResourceAsStream("/scoring/scoring-vectors.json")) {
            assertThat(stream).as("the pinned vectors").isNotNull();
            return MAPPER.readTree(stream);
        }
    }

    private List<ScoredPlayer> pool(JsonNode rows) {
        List<ScoredPlayer> pool = new ArrayList<>();
        for (JsonNode row : rows) {
            Set<String> positions = new LinkedHashSet<>(strings(row.get("positions")));
            pool.add(new ScoredPlayer(
                    row.get("playerId").asInt(),
                    row.get("name").asText(),
                    "goalie".equals(row.get("type").asText()),
                    positions,
                    numbers(row.get("stats").get("scoring")),
                    numbers(row.get("stats").get("utility"))));
        }
        return pool;
    }

    private List<LeagueSummaryCalculator.TeamPicks> teams(JsonNode rows) {
        List<LeagueSummaryCalculator.TeamPicks> teams = new ArrayList<>();
        for (JsonNode row : rows) {
            List<Integer> picks = new ArrayList<>();
            row.get("playerIds").forEach(pick -> picks.add(pick.asInt()));
            teams.add(new LeagueSummaryCalculator.TeamPicks(
                    row.get("teamId").asText(),
                    row.get("name").asText(),
                    row.get("mine").asBoolean(),
                    picks));
        }
        return teams;
    }

    private LeagueScoring league(JsonNode league) {
        JsonNode slots = league.get("rosterSlots");
        return LeagueScoring.of(
                "points".equals(league.get("scoringType").asText()),
                numbers(league.get("statWeights")),
                strings(league.get("activeScoringColumns")),
                new RosterSlots(
                        slots.get("c").asInt(),
                        slots.get("lw").asInt(),
                        slots.get("rw").asInt(),
                        slots.get("d").asInt(),
                        slots.get("util").asInt(),
                        slots.get("bn").asInt(),
                        slots.get("g").asInt()),
                league.get("leagueSize").asInt(),
                league.get("minGoalieGames").asInt(),
                null);
    }

    private Map<String, Double> numbers(JsonNode node) {
        Map<String, Double> values = new LinkedHashMap<>();
        node.fieldNames().forEachRemaining(key -> values.put(key, node.get(key).asDouble()));
        return values;
    }

    private List<String> strings(JsonNode node) {
        List<String> values = new ArrayList<>();
        node.forEach(entry -> values.add(entry.asText()));
        return values;
    }

    private List<String> fieldNames(JsonNode node) {
        List<String> names = new ArrayList<>();
        node.fieldNames().forEachRemaining(names::add);
        return names;
    }
}
