package com.fantasy.bff.service.scoring;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import com.fantasy.bff.dto.response.RosterSlots;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Holds this engine to the web's, player by player.
 *
 * <p>Two implementations of one ranking is a thing that drifts, and a league scored differently
 * on two surfaces is worse than a league not scored here at all: the board a manager drafted on
 * and the summary he is sent afterwards would disagree about who won his draft. So the numbers
 * are not compared by eye or by property — the web computes them, commits them
 * (`fantasy-web/src/app/draft-mode/scoring-vectors.json`, generated by its own spec) and this
 * test replays the same leagues through the Java engine.
 *
 * <p>What is held is what each player is worth: his value and his share of every category cell,
 * which is the arithmetic both sides share. What a team adds up to is not: the web adds a drafted
 * roster up whole, while this counts each player for the share of his games his team's best
 * lineup starts him in, night by night over the schedule (fantasy-bff#363). So the committed
 * vectors' team totals, cells and lineups are no longer compared, only their roster rows, each
 * a player's whole value.
 *
 * <p>On a deliberate change to how a board is scored: change the web, regenerate there with
 * `UPDATE_SCORING_VECTORS=1 npm test`, and re-pin the file here in the same change, the way a
 * downstream spec is pinned. A failure with no such change means one side moved on its own.
 */
class LeagueSummaryGoldenVectorTest {

    /** The numbers are the same arithmetic in both languages; this is room for the last bit. */
    private static final double TOLERANCE = 1e-9;

    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Test
    @DisplayName("scores every player in every committed league exactly as the web scored him")
    void matchesTheWebsVectors() throws Exception {
        JsonNode vectors = readVectors();
        assertThat(vectors.get("cases")).as("committed cases").isNotEmpty();

        for (JsonNode entry : vectors.get("cases")) {
            JsonNode testCase = entry.get("case");
            String name = testCase.get("name").asText();
            List<ScoredPlayer> pool = pool(testCase.get("pool"));
            LeagueScoring league = league(testCase.get("league"));
            ProjectionScoring.Scores scores = ProjectionScoring.score(pool, league);
            Map<String, ScoredPlayer> byName = new LinkedHashMap<>();
            pool.forEach(player -> byName.putIfAbsent(player.name(), player));

            JsonNode expected = entry.get("expected");
            assertThat(league.activeScoringColumns()).as("%s: category keys", name)
                    .isEqualTo(strings(expected.get("categoryKeys")));
            for (JsonNode expectedTeam : expected.get("teams")) {
                String where = "%s: %s".formatted(name, expectedTeam.get("teamId").asText());
                for (JsonNode expectedRow : expectedTeam.get("roster")) {
                    ScoredPlayer player = byName.get(expectedRow.get("name").asText());
                    assertThat(player).as("%s: %s in the pool", where, expectedRow.get("name").asText()).isNotNull();
                    assertRow(where, LeagueSummaryCalculator.rosterRow(
                            player, scores, league.activeScoringColumns(), 1, false, true), expectedRow);
                }
            }
        }
    }

    private void assertRow(String where, LeagueSummary.RosterRow row, JsonNode expectedRow) {
        String rowWhere = "%s: %s".formatted(where, row.name());
        assertThat(row.total()).as("%s total", rowWhere)
                .isCloseTo(expectedRow.get("total").asDouble(), within(TOLERANCE));
        assertNullableNumbers(rowWhere + " values", row.values(), expectedRow.get("values"));
        assertNullableNumbers(rowWhere + " contributions", row.contributions(), expectedRow.get("contributions"));
    }

    /**
     * A stat of the other kind is null rather than zero — a goalie has no hits, which is not the
     * same as a goalie who lands none — so the nulls are part of what has to match.
     */
    private void assertNullableNumbers(String where, Map<String, Double> actual, JsonNode expected) {
        assertThat(actual.keySet()).as("%s: keys", where)
                .containsExactlyInAnyOrderElementsOf(fieldNames(expected));
        expected.fieldNames().forEachRemaining(key -> {
            JsonNode value = expected.get(key);
            if (value.isNull()) {
                assertThat(actual.get(key)).as("%s: %s", where, key).isNull();
            } else {
                assertThat(actual.get(key)).as("%s: %s", where, key)
                        .isCloseTo(value.asDouble(), within(TOLERANCE));
            }
        });
    }

    private JsonNode readVectors() throws Exception {
        try (InputStream stream =
                getClass().getResourceAsStream("/scoring/scoring-vectors.json")) {
            assertThat(stream).as("the pinned vectors").isNotNull();
            return MAPPER.readTree(stream);
        }
    }

    private List<ScoredPlayer> pool(JsonNode rows) {
        List<ScoredPlayer> pool = new ArrayList<>();
        for (JsonNode row : rows) {
            Set<String> positions = new LinkedHashSet<>(strings(row.get("positions")));
            pool.add(new ScoredPlayer(
                    row.get("playerId").asInt(),
                    row.get("name").asText(),
                    null,
                    "goalie".equals(row.get("type").asText()),
                    positions,
                    numbers(row.get("stats").get("scoring")),
                    numbers(row.get("stats").get("utility"))));
        }
        return pool;
    }

    private LeagueScoring league(JsonNode league) {
        JsonNode slots = league.get("rosterSlots");
        return LeagueScoring.of(
                "points".equals(league.get("scoringType").asText()),
                numbers(league.get("statWeights")),
                strings(league.get("activeScoringColumns")),
                new RosterSlots(
                        slots.get("c").asInt(),
                        slots.get("lw").asInt(),
                        slots.get("rw").asInt(),
                        slots.path("w").asInt(),
                        slots.path("f").asInt(),
                        slots.get("d").asInt(),
                        slots.get("util").asInt(),
                        slots.get("bn").asInt(),
                        slots.get("g").asInt()),
                league.get("leagueSize").asInt(),
                league.get("minGoalieGames").asInt(),
                null);
    }

    private Map<String, Double> numbers(JsonNode node) {
        Map<String, Double> values = new LinkedHashMap<>();
        node.fieldNames().forEachRemaining(key -> values.put(key, node.get(key).asDouble()));
        return values;
    }

    private List<String> strings(JsonNode node) {
        List<String> values = new ArrayList<>();
        node.forEach(entry -> values.add(entry.asText()));
        return values;
    }

    private List<String> fieldNames(JsonNode node) {
        List<String> names = new ArrayList<>();
        node.fieldNames().forEachRemaining(names::add);
        return names;
    }
}
