name: Qodana

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: qodana-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.1
        continue-on-error: true
        with:
          pr-mode: false
          upload-result: true
